#!/bin/bash
source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_script_progression "Backing up app files..."
ynh_backup "$install_dir"

ynh_script_progression "Backing up data..."
ynh_backup "$data_dir"

ynh_script_progression "Backup done."
