#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Restoring application files..."
ynh_restore "$install_dir"

ynh_script_progression "Restoring data..."
ynh_restore "$data_dir"
chown -R "$app:$app" "$data_dir"

ynh_script_progression "Restoring nginx configuration..."
ynh_restore_conf_nginx

ynh_script_progression "Restoring systemd service..."
ynh_restore_conf_systemd
yunohost service add "$app" --description="D&D 3.5 character sheet" --log="/var/log/$app/error.log"

ynh_script_progression "Recreating log directory..."
mkdir -p "/var/log/$app"
chown "$app:$app" "/var/log/$app"

ynh_script_progression "Starting service..."
ynh_systemctl start "$app.service"

ynh_script_progression "Restore complete!"
