#!/bin/bash
source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_script_progression "Restoring app files..."
ynh_restore "$install_dir"

ynh_script_progression "Restoring data..."
ynh_restore "$data_dir"
chown -R "$app:$app" "$data_dir"

ynh_script_progression "Reconfiguring nginx..."
ynh_config_add_nginx

ynh_script_progression "Reconfiguring systemd..."
ynh_config_add_systemd
yunohost service add "$app" --description="D&D 3.5 character sheet" --log="/var/log/$app/error.log"

mkdir -p "/var/log/$app"
chown "$app:$app" "/var/log/$app"

ynh_script_progression "Starting service..."
ynh_systemctl --action=start --service="$app.service"

ynh_script_progression "Restore done."
